### ISSUE TITLE
TypeError: Cannot call method 'unprepare' of undefined

### ISSUE THREAD

**Issue by batjko** [emgee3/meteor-mssql#8]
Hi there,

I'm having trouble getting a prepared statement to work.
Granted, I have never used the underlying mssql package before.

This is the error I am getting when launching Meteor:

```
W20150828-10:32:29.763(1)? (STDERR) C:\Users\tthpmx\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150828-10:32:29.764(1)? (STDERR)                                             throw(ex);
W20150828-10:32:29.764(1)? (STDERR)                                                   ^
W20150828-10:32:29.764(1)? (STDERR) TypeError: Cannot call method 'unprepare' of undefined
W20150828-10:32:29.764(1)? (STDERR)     at app\server\sqltest.js:30:10
W20150828-10:32:29.764(1)? (STDERR)     at c:\Git\meteor-sql-test\.meteor\local\build\programs\server\boot.js:229:5
=> Exited with code: 8
```

As described, I have put my connection settings object into a settings.json file and started Meteor with `meteor --settings settings.json`.

And this is the code I am trying to execute (in my server folder, so it's server-side only):

``` javascript
Meteor.startup(function () {
  var opts = {
       query : "select * from Table_1 where age < @age",
       inputs : [
         {name : 'age', type: Sql.driver.Int, value: 100}
       ]
     };

   var query = Sql.ps(opts, function(err, results){
     if (err){
       console.error(err);
       throw new Meteor.Error(err);
     }

     console.log(results);

   });

   query.unprepare();
});
```

Probably something very dumb I've forgotten, any idea?

**Comment by batjko** [comment]
Update:

So I tried commenting out the unprepare call, and Meteor then starts, tries to connect, but then fails with this ConnectionError:
![image](https://cloud.githubusercontent.com/assets/7287076/9543994/20c1e2e6-4d75-11e5-9444-3bb715640766.png)

These are the settings I have in my `settings.json` file:

``` json
{
  "database": {
    "server"   : "localhost\\SQLEXPRESS",
    "database" : "FAKE_FINDUR",
    "user"     : "meteor",
    "password" : "meteor",
    "options"  : {
      "useUTC"     : false,
      "appName"    : "MeteorTest"
    }
  }
}
```

Note, I can confirm that I am perfectly able to connect with those settings, if I use SQL Server Management Studio:
![image](https://cloud.githubusercontent.com/assets/7287076/9544068/8b781830-4d75-11e5-9214-fe6a44f1271f.png)

**Comment by batjko** [comment]
I think I figured it out. I didn't have the Browser Service running for SQL. When I turned this on, the connection seemed to be fine.

I am now running into issues more specific to the prepared statement, but that's different. So I'll close this off.
